/*
 * React Gin SPA Practice API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"flag"
	"fmt"
	"log"

	// WARNING!
	// Pass --git-repo-id and --git-user-id properties when generating the code
	//
	sw "github.com/shohei-ot/react-gin-spa-practice/go"
)

func main() {
	port := flag.String("port", "8080", "Port to listen on")
	flag.Parse()

	routes := sw.ApiHandleFunctions{}

	log.Printf("Server started on port %s", *port)

	router := sw.NewRouter(routes)

	prepare(router)

	log.Fatal(router.Run(fmt.Sprintf(":%s", *port)))
}
