/*
 * React Gin SPA Practice API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"github.com/gin-gonic/gin"
)

type DefaultAPI struct {
}

// Get /api/ping2
func (api *DefaultAPI) ApiPing2Get(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"message": "pong2"})
}

// Get /api/ping
func (api *DefaultAPI) ApiPingGet(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"message": "pong"})
}
