/*
 * React Gin SPA Practice API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ApiPing2Get200Response struct {

	Message string `json:"message,omitempty"`
}
